### ISSUE TITLE
Interfaz Angular. Error CORS

### ISSUE THREAD

**Issue by danbenveg** [EGC-decide-bailon/angular-decide-bailon#11]

**Comment by Acunnia** [comment]
He probado a usar las URL de la app desplegada y continuamos con el mismo error. Incluso usando un servidor proxy intermediario para realizar las peticiones. Colocar los headers que pide el error a la petición HTTP no cambia el error.

**Comment by laubezqueoff** [comment]
Pido una tutoría con el profesor para intentar resolverlo.

**Comment by laubezqueoff** [comment]
Nos ha contestado con lo siguiente :"He estado mirando y creo que el problema que os está pasando es debido a que tenéis lo que el propio mensaje os transmite: un problema CORS:
https://developer.mozilla.org/es/docs/Web/HTTP/Access_control_CORS

El mecanismo impide que haya peticiones cruzadas desde orígenes distintos. En vuestro caso desde el origen que sirve AngularJS a la API de Decide. Cada uno de ellos, a buen seguro, los tenéis en servidores disintos por lo que se activa ese mecanismo de control CORS.

Para poder solucionarlo habría varias alternativas:
(A) Montar en un mismo servidor (por ejemplo Nginx) tanto la parte de Angular como Decide. Aquí os paso un enlace de cómo está hecho en Decide con docker: (a

https://github.com/EGCETSII/decide/blob/master/docker/docker-nginx.conf

(B) Configurar bien la app "coarse headers" que podéis ver aquí configurada en el settings:

https://github.com/EGCETSII/decide/blob/master/decide/decide/settings.py#L41

Sin embargo, no estaría del todo configurada para dar acceso desde fuera. Para ello tendrías que seguir algunos pasos adicionales.
Por aquí podéis ver alguna información al respecto con enlaces útiles:

https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework

Y por aquí un vídeo en español que algo ilustrativo es.

https://www.hektorprofe.net/curso/spa-frontend-web-api-auth-vue-nuxt/peticiones-cors-api-django

Esto os permitiría dar permisos a otros "origin" para acceder a la API de Decide, como en vuestro caso, el servidor donde tenéis el AngularJS.
Cuidado, no sigáis al pie de la letra todas las cosas que se dicen, más bien adaptadlo a vuestras circunstancias."

Me pongo yo con la alternativa A del servidor Nginx, ponte tu con la otra

**Comment by Acunnia** [comment]
> Me pongo yo con la alternativa A del servidor Nginx, ponte tu con la otra

Tras leer toda la documentación y configurar Django para usar cors-headers. Sigue con el mismo error, sin cambio alguno.

He visto que Decide utiliza un gateway para realizar las peticiones a la API, he probado a lanzar las versiones antiguas de Decide pero me arroja errores python.

**Comment by laubezqueoff** [comment]
Yo también he probado la opción ha y he obtenido el mismo problema. Voy a contactar con el profesor de prácticas para otra tutoría.

**Comment by laubezqueoff** [comment]
El profesor me ha respondido, tenemos reunión el día 12 de enero a las 12:30.

**Comment by laubezqueoff** [comment]
Solución del problema: hemos instalado una extensión para firefox, "CORS Unblock" que permite bloquear el CORS.
