### ISSUE TITLE
Interfaz Angular. Conectar aplicación con Decide

### ISSUE THREAD

**Issue by laubezqueoff** [EGC-decide-bailon/angular-decide-bailon#4]

**Comment by Acunnia** [comment]
Tengo un problema con el CORS. A la hora de realizar las peticiones a Decide, esta, rechaza todas las peticiones arrojando este error: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/gateway/authentication/login/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/gateway/authentication/login/. (Reason: CORS request did not succeed).

**Comment by danbenveg** [comment]
Prueba a hacer las peticiones con la versión de Decide desplegada en Heroku, creo una issue para seguir tratando el problema.
